"use client";

import { useState } from "react";
import Link from "next/link";
import { useTranslations } from "next-intl";
import { Button } from "@/components/ui/button";
import { useContent } from "@/hooks/use-content";
import { useHeroImage } from "@/hooks/use-hero-image";
import { heroOverlayBackground } from "@/lib/hero-overlay";
import { cn } from "@/lib/utils";
import { HeroImageControls } from "./hero-image-controls";
import { ProductPreview } from "./product-preview";
import { config } from "@/lib/prototype-config";
import { landingActionHref } from "@/lib/landing-action";

/**
 * Hero section — the first thing a visitor sees.
 *
 * Headline and subheadline come from `prototype.config.json` when present, with
 * translations as a fallback. Sonnet writes the config values; the translations are just
 * placeholders for local dev and to keep the template buildable before any content agent
 * has touched it.
 *
 * The section spans the full width so an AI background image (generated by the
 * prototype's creator or the founder, see `lib/hero-image.ts`) can fill it; the content
 * keeps its old `max-w-5xl` box, so without an image the hero looks exactly as before.
 * The image layer is absolutely positioned: it moves nothing (CLS 0) and is decoration,
 * not content — hidden from assistive tech and fetched at low priority so it never
 * competes with the headline for LCP.
 */

function HeroBackground({ src }: { src: string }) {
  const [loaded, setLoaded] = useState(false);
  return (
    <div aria-hidden className="pointer-events-none absolute inset-0 -z-10">
      {/* next/image cannot optimise in a static export; this is a plain decorative img. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img
        data-hero-image
        src={src}
        alt=""
        decoding="async"
        fetchPriority="low"
        onLoad={() => setLoaded(true)}
        className={cn(
          "h-full w-full object-cover transition-opacity duration-700 motion-reduce:transition-none",
          loaded ? "opacity-100" : "opacity-0"
        )}
      />
      <div className="absolute inset-0" style={{ background: heroOverlayBackground() }} />
    </div>
  );
}

export function HeroSection() {
  const t = useTranslations("landing");
  const content = useContent();
  const landing = content.landing;
  const href = landingActionHref(config.patterns);
  const headline = landing?.headline ?? t("title");
  const subheadline = landing?.subheadline ?? t("subtitle");
  const hero = useHeroImage();
  const hasPreview = Boolean(config.patterns.dataGrid && content.dataGrid?.sampleRecords?.length);

  return (
    <section data-section="hero" className="relative isolate w-full overflow-hidden">
      {hero.src ? <HeroBackground key={hero.src} src={hero.src} /> : null}
      <div
        className={cn(
          "mx-auto grid w-full max-w-5xl gap-10 px-4 py-20 sm:py-28",
          hasPreview && "lg:grid-cols-2 lg:items-center"
        )}
      >
        <div
          className={cn(
            "flex flex-col items-center gap-6 text-center",
            hasPreview && "lg:items-start lg:text-left"
          )}
        >
          <p data-app-name className="text-sm font-medium uppercase tracking-widest text-muted-foreground">
            {config.appName}
          </p>
          <h1 className="text-balance text-4xl font-semibold tracking-tight sm:text-5xl">{headline}</h1>
          <p className="max-w-xl text-balance text-muted-foreground sm:text-lg">{subheadline}</p>
          {href && (
            <Button asChild size="lg" className="h-11">
              <Link href={href}>{content.cta?.label ?? t("cta")}</Link>
            </Button>
          )}
        </div>
        {hasPreview && <ProductPreview />}
      </div>
      <HeroImageControls hero={hero} />
    </section>
  );
}
