/**
 * Renders `styles.css` from the font table and `fonts/manifest.json`. Pure — no network,
 * no file writes — so `test/fonts.test.ts` can regenerate it and compare with what is
 * committed. The only writer is `fetch-fonts.ts`.
 */
import {
  ALL_FONT_FACES,
  FIXED_FONTS,
  FONT_FAMILIES,
} from "../src/theming/font-families";

export interface FontFile {
  /** Relative to the package root, e.g. `fonts/inter/latin.woff2`. */
  file: string;
  subset: string;
  /** `400` for a static face, `100 900` for a variable one — exactly as Google declared it. */
  weight: string;
  unicodeRange: string;
}

/** Keyed by face id. */
export type FontManifest = Record<string, FontFile[]>;

/** How the CSS declares a face's weights — the string Google's own @font-face carries. */
export function declaredWeights(
  weights: readonly number[] | { min: number; max: number }
): string[] {
  return "min" in weights ? [`${weights.min} ${weights.max}`] : weights.map(String);
}

export function renderStylesCss(manifest: FontManifest): string {
  const faces: string[] = [];
  for (const face of ALL_FONT_FACES) {
    const family = face.stack.match(/^"([^"]+)"/)![1];
    for (const f of manifest[face.id] ?? []) {
      faces.push(
        [
          "@font-face {",
          `  font-family: "${family}";`,
          "  font-style: normal;",
          `  font-weight: ${f.weight};`,
          // swap, not block: text must never be invisible while a 30 kB file loads.
          "  font-display: swap;",
          `  src: url("./${f.file}") format("woff2");`,
          `  unicode-range: ${f.unicodeRange};`,
          "}",
        ].join("\n")
      );
    }
  }

  const choices = FONT_FAMILIES.map(
    (f) => `html[data-font="${f.id}"] {\n  --shared-font-sans: ${f.stack};\n}`
  );

  return [
    "/* GENERATED by scripts/fetch-fonts.ts from src/theming/font-families.ts — do not edit. */",
    "",
    "/* Fixed faces: the brand does not follow the visitor's font choice. The sans default",
    "   applies until the host sets html[data-font]. */",
    ":root {",
    `  --shared-font-display: ${FIXED_FONTS.display.stack};`,
    `  --shared-font-mono: ${FIXED_FONTS.mono.stack};`,
    `  --shared-font-sans: ${FONT_FAMILIES[1].stack};`,
    "}",
    "",
    ...choices.flatMap((c) => [c, ""]),
    ...faces.flatMap((f) => [f, ""]),
  ].join("\n");
}
