export { Header, type HeaderProps } from "./header/Header";
export { DEFAULT_LABELS, format, type HeaderLabels } from "./header/labels";
export { navFor, type HeaderVariant, type NavItem } from "./header/nav";
export { Wordmark, type LogoProps } from "./brand/Wordmark";
export type { LanguageLink } from "./switchers/LanguageSwitcher";
export type { CartProps } from "./cart/CartButton";
export type { HeaderUser, UserMenuItem } from "./user-menu/UserMenu";
export { ThemeBootstrap, themeBootstrapScript } from "./theming/ThemeBootstrap";
export * from "./theming";
export { VERSION } from "./version";
